#!/usr/bin/python3

import sys

def factorize_number(number):
    divisor = 2
    while number % divisor != 0:
        divisor += 1
    p = number // divisor
    return f"{number}={p}*{divisor}"

def main():
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    try:
        with open(input_file, 'r') as file:
            for line in file:
                number = int(line.strip())
                print(factorize_number(number))

    except FileNotFoundError:
        print(f"File '{input_file}' not found.")
        sys.exit(1)
    except ValueError:
        print("Invalid number in the file.")
        sys.exit(1)

if __name__ == "__main__":
    main()

